  global:
    scrape_interval: 15s

  scrape_configs:
  - job_name: 'notification-orchestrator-app'
    static_configs:
      - targets: ['notification-orchestrator:8080']
  - job_name: 'email-worker-app'
    static_configs:
      - targets: ['email-worker:8080']
  - job_name: 'sms-worker-app'
    static_configs:
      - targets: ['sms-worker:8080']
  - job_name: 'slack-worker-app'
    static_configs:
      - targets: ['slack-worker:8080']
  