server:
  port: 8080
kafka:
  bootstrap-servers: localhost:9092
  required-acks: 1
  max-retries: 3
notifications:
  channel-topics:
    slack: slack-worker
    email: email-worker
    sms: sms-worker
  dead-letter-topic: notifications-dlq