server:
  port: 8080
kafka:
  bootstrap-servers: kafka:29092
  producer:
    required-acks: 1
    max-retries: 3
    message-channel-buffer: 1000
    worker-pool: 10
    batch-size: 1 #this is only for testing purposes
    batch-timeout-ms: 150
  consumer:
    email-topic: slack-worker
    group-id: slack-worker
    enable-auto-commit: false
    message-channel-buffer: 1000
    worker-pool: 100
