server:
  port: 8080
kafka:
  bootstrap-servers: localhost:9092
  producer:
    required-acks: 1
    max-retries: 3
    message-channel-buffer: 1000
  consumer:
    email-topic: email-worker
    group-id: email-worker
    enable-auto-commit: false
    message-channel-buffer: 1000
